baseURL = "https://codumn.com/"
title = "键盘侠的部落格"
theme = "hugo-primer"
languageCode = "zh-cn"
hasCJKLanguage = true
summaryLength = 70
# Code pen
pygmentsCodeFences = true
pygmentsUseClasses = true

googleAnalytics = "G-NEYBRQCFCC"
copyright = "&copy;Jackie 2020"

enableEmoji = true

[frontmatter]
  # update sitemap.xml's lastmod datetime by file change time, instead of git.
  # lastmod = ["lastmod", ":fileModTime", ":default"]
[params]
  description = "金键盘奖优秀键盘侠"
  twitter = 'iceiceiceJack'
  # You can use favicon by adding `favicon-64.png` to `static` directory.
  # You can also add `apple-touch-icon.png` and `pinned-icon.svg`.
  useIcon = true
  useTwitterCard = true
  # Use MathJax.js. Disabling site-wide and you still can enable in indivisual pages
  math = true
  # Chose Social Sharing Buttons you want to use.
  shareTo = ["Twitter", "Facebook"]
  # You may disable copyright sentence by setting this to false.
  showFooterCredits = true

